<?php
/**
 * 
 *
 * @author Joseph Maxwell
 * @copyright Swift Otter Studios, 3/14/13
 * @package default
 **/

class SwiftOtter_Inventory_Block_Admin_Report_SalesOrdering_Filter extends SwiftOtter_Base_Block_Admin_Form_Filter
{
    /**
     * @param Varien_Data_Form_Element_Fieldset $fieldset
     * @return $this
     */
    protected function _addAdditionalFields($fieldset, $filter)
    {
        $fieldset->addField('reorder_timeframe', 'select', array(
            'label' => $this->__('Reorder Timeframe'),
            'name'  => 'reorder_timeframe',
            'id'    => 'reorder_timeframe',
            'class' => 'form-custom',
            'type' => 'options',
            'options' => array(
                '15' => $this->__('15 days'),
                '30' => $this->__('30 days'),
                '60' => $this->__('60 days'),
                '90' => $this->__('90 days'),
                '180' => $this->__('180 days'),
                '360' => $this->__('360 days'),
                '' => $this->__('Specified per Vendor')
            )
        ));



        return parent::_addAdditionalFields($fieldset, $filter);
    }

//    protected function _formatInputParams($params)
//    {
//
//        return parent::_formatInputParams($params); // TODO: Change the autogenerated stub
//    }


}