<?php
/** @var SwiftOtter_Inventory_Block_Email_DropShipNotification $this */
?>

<h2><?php echo $this->__('Alert for %s', $this->getVendor()->getName());?></h2>
<h3><?php echo $this->__('Order: %s', $this->getOrder()->getIncrementId());?></h3>
<h3>For: <a href="mailto:<?php echo $this->getOrder()->getCustomerEmail();?>">
        <?php echo $this->getOrder()->getCustomerFirstname();?> <?php echo $this->getOrder()->getCustomerLastname();?></a></h3>

<?php if (!$this->getOrder()->getIsVirtual()):?>
    <?php $address = $this->getOrder()->getShippingAddress();?>
<h4><?php echo $this->__('Shipping to:');?></h4>
<ul>
    <li><?php echo $address->getName();?></li>
    <?php if ($address->getCompany()):?>
    <li><?php echo $address->getCompany();?></li>
    <?php endif;?>
    <?php for ($i = 1; $i <= 4; $i++):?>
        <?php if ($address->getStreet($i)):?>
        <li><?php echo $address->getStreet($i);?></li>
        <?php endif;?>
    <?php endfor;?>
    <li><?php echo $address->getCity();?>, <?php echo $address->getRegionCode();?> <?php echo $address->getPostcode();?></li>
    <?php if ($shippingDescription = $this->getOrder()->getShippingDescription()):?>
        <li><?php echo $shippingDescription;?></li>
    <?php endif;?>
</ul>
<?php endif;?>

<table bgcolor="#FFFFFF" cellspacing="0" cellpadding="10" border="0" width="650" style="border:1px solid #E0E0E0;">
    <tr>
        <td bgcolor="#EAEAEA" align="center" style="background:#EAEAEA; text-align:center;"><center><p style="font-size:12px; margin:0;"><strong>SKU</strong></p></center></td>
        <td bgcolor="#EAEAEA" align="center" style="background:#EAEAEA; text-align:center;"><center><p style="font-size:12px; margin:0;"><strong>Vendor SKU</strong></p></center></td>

        <td bgcolor="#EAEAEA" align="center" style="background:#EAEAEA; text-align:center;"><center><p style="font-size:12px; margin:0;"><strong>Product</strong></p></center></td>
        <td bgcolor="#EAEAEA" align="center" style="background:#EAEAEA; text-align:center;"><center><p style="font-size:12px; margin:0;"><strong>QTY Ordered</strong></p></center></td>
    </tr>
    <?php /** @var Mage_Catalog_Model_Product $product */ ?>
    <?php foreach($this->getProducts() as $product):
    ?>
    <tr>
        <td style="text-align:center"><?php echo $product->getSku();?></td>
        <td style="text-align:center"><?php echo $product->getVendorSku();?></td>
        <td style="text-align:center"><?php echo $product->getName();?></td>
        <td style="text-align:center"><?php echo round($product->getQty());?></td>
    </tr>
    <?php endforeach;?>
</table>